baseURL = "https://www.sufishientcharters.com/"
languageCode = "en-us"
title = "SuFISHient Charters"
theme = "hero"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "SuFISHient Charters: See photos, check our rates, and book a fishing trip. Sailing out of Holland, Grand Haven, or Saugatuck on beautiful Lake Michigan."
    meta_og_title = "SuFISHient Charters | Book your fishing trip | Holland, Michigan"
    meta_og_type = "website"
    meta_og_url = "https://www.sufishientcharters.com/"
    meta_og_image = "https://www.sufishientcharters.com/wp-content/uploads/2017/09/IMG_2320.jpg"
    meta_og_description = "SuFISHient Charters: see photos, check our rates, and book a fishing trip. Sailing out of Holland, Grand Haven, or Saugatuck on beautiful Lake Michigan."
    meta_twitter_card = "summary_large_image"
    meta_twitter_image = "https://www.sufishientcharters.com/wp-content/uploads/2017/09/IMG_2320.jpg"
    meta_twitter_site = "@sufishientcharters"
    meta_twitter_creator = "@sufishientcharters"

[[menu.main]]
	name = "Charters"
	url = "/charters/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Location"
    url = "/history/"
    weight = 4

[[menu.main]]
    name = "Book"
    url = "/contact/"
    weight = 5

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
