[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.82.0"
  HUGO_THEME = "hero"
  HUGO_BASEURL = "https://sufishientcharters.com/"

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404
